import type { Metadata } from "next";
import localFont from "next/font/local";
import styles from "./page.module.css";
import { ReactNode } from "react";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={styles.page}>
          <main className={styles.main}>{children}</main>
        </div>
        {/* <Footer /> */}
        {/* <MobileMenu /> */}
        {/* <ToastContainer /> */}
      </body>
    </html>
  );
}
